spring.application.name=springboot-employee-layered-ioc-project

app.driverclassname=oracle.jdbc.driver.OracleDriver
app.url=jdbc:oracle:thin:@localhost:1521:XE

spring.profiles.active=prod

#Logging Levels
#TRACE
#DEBUG
#INFO
#WARN
#ERROR

logging.file.name=employeeapp.log
