spring.application.name=springboot-rest-api-employee-project

info.app.name=Employee Management System
info.app.version=1.0
info.company=Sujata DXC Training Batch
info.environment=Learning

#Oracle DataBase Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=sujata
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# update: if table is already there use that otherwise create the table based on mapping specified in entity class
spring.jpa.hibernate.ddl-auto=update

#Show SQL Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#server port
server.port=8085

#Logging
#logging.level.root=INFO
#logging.file.name=logs/employee.log

#actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

