spring.application.name=springboot-first-data-jpa-project

#Oracle DataBase Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=sujata
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# update: if table is already there use that otherwise create the table based on mapping specified in entity class
spring.jpa.hibernate.ddl-auto=update
#Show SQL Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#Connection Pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=EmployeePayrollProjectPool