spring.application.name=springboot-first-data-jpa-project

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.username=root
spring.datasource.password=sujata
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#Store 50 SQL statements in memory, send them together to database
spring.jpa.properties.hibernate.jdbc.batch_size=50

#Groups similar inserts
#Instead of:
#Employee
#Payroll
#Employee
#Payroll
#Employee
#Payroll

#Hibernate rearranges:
#Payroll
#Payroll
#Payroll
#Employee
#Employee
#Employee

#This improves batching.
spring.jpa.properties.hibernate.order_inserts=true

#Groups update statements together.
spring.jpa.properties.hibernate.order_updates=true
