spring.application.name=springboot-logging-actuator-metrics-demo-project

#Oracle DataBase Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=sujata
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# update: if table is already there use that otherwise create the table based on mapping specified in entity class
spring.jpa.hibernate.ddl-auto=update

#Show SQL Queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.port=8085
server.port=8087

#loggingserver.port=808
logging.level.root=INFO
logging.level.com.sujata=DEBUG
logging.file.name=logs/employee.log

#actuators
management.endpoints.web.exposure.include=*

